{{- $useNfs := .Values.nfs.enabled -}}

{{- if not $useNfs }}
{{- range $name, $size := .Values.deployment.spec.nodesSharedDisk }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}
  labels:
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  storageClassName: {{ $.Values.defaultStorageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $size }}
{{- end }}
{{- end }}