apiVersion: v1
kind: Secret
metadata:
  name: su
  labels:
    {{- with .Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  suPass: {{ .Values.su.pass | b64enc }}
  suPassHash: {{ .Values.su.passHash | b64enc }}
