{{- range $nodeGroupName, $nodeGroup := .Values.deployment.spec.nodeGroups }}
{{- $useNfs := $.Values.nfs.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $nodeGroupName }}
  labels:
    nodeGroup: {{ $nodeGroupName }}
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  serviceName: {{ $nodeGroupName }}
  replicas: {{ $nodeGroup.replicas }}
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      nodeGroup: {{ $nodeGroupName }}
      {{- with $.Values.defaultLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      annotations:
        {{- if $.Values.extensions.linkerd }}
        linkerd.io/inject: enabled
        {{- end }}
      labels:
        nodeGroup: {{ $nodeGroupName }}
        {{- with $.Values.defaultLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30

      securityContext:
        fsGroup: 0
        runAsUser: 1337

      initContainers:
        - name: configure-sysctl
          image: {{ $.Values.image }}
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          securityContext:
            privileged: true
            runAsUser: 0
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144

      containers:
        - name: exp
          image: {{ $.Values.image }}
          imagePullPolicy: {{ $.Values.imagePullPolicy }}

          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1337

          resources:
            limits:
              cpu: {{ $nodeGroup.resources.cpu }}
              memory: {{ $nodeGroup.resources.memory }}
            requests:
              cpu: {{ $nodeGroup.resources.cpu }}
              memory: {{ $nodeGroup.resources.memory }}

          ports:
          - name: xp-stats
            containerPort: 2609
            protocol: TCP
          - name: xp-main
            containerPort: 8080
            protocol: TCP
          - name: es-http
            containerPort: 9200
            protocol: TCP
          - name: es-transport
            containerPort: 9300
            protocol: TCP

          env:
          - name: XP_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: XP_NODE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: SU_PASS_HASH
            valueFrom:
              secretKeyRef:
                name: su
                key: suPassHash
                optional: false

          livenessProbe:
            {{- with $.Values.livenessProbe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

          readinessProbe:
            {{- with $.Values.readinessProbe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

          volumeMounts:
            {{- range $volumeName, $volumeSize := $nodeGroup.resources.disks }}
            - name: {{ $volumeName }}
              mountPath: {{ index $.Values.volumeMounts $volumeName }}
            {{- end }}
            {{- if $useNfs }}
              {{- range $volumeName, $volumeSize := $.Values.deployment.spec.nodesSharedDisk }}
            - name: shared
              mountPath: {{ index $.Values.volumeMounts $volumeName }}
              subPath: {{ $.Values.deployment.name }}/{{ $volumeName }}
              {{- end }}
            {{- else }}
              {{- range $volumeName, $volumeSize := $.Values.deployment.spec.nodesSharedDisk }}
            - name: {{ $volumeName }}
              mountPath: {{ index $.Values.volumeMounts $volumeName }}
              {{- end }}
            {{ end }}
      volumes:
        - name: config
          configMap:
            name: {{ $nodeGroupName }}
        {{- if $useNfs }}
        - name: shared
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.path }}
        {{- else }}
          {{- range $volumeName, $volumeSize := $.Values.deployment.spec.nodesSharedDisk }}
        - name: {{ $volumeName }}
          persistentVolumeClaim:
            claimName: {{ $volumeName }}
          {{- end }}
        {{- end }}

  volumeClaimTemplates:
    {{- range $volumeName, $volumeSize := $nodeGroup.resources.disks }}
    - metadata:
        name: {{ $volumeName }}
        labels:
          nodeGroup: {{ $nodeGroupName }}
          {{- with $.Values.defaultLabels }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      spec:
        storageClassName: {{ $.Values.defaultStorageClass }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ $volumeSize }}
    {{- end }}
{{- end }}