apiVersion: v1
name: xp-operator
version: 0.0.0
appVersion: 0.0.0
home: https://github.com/enonic/xp-operator
description: Enonic XP Kubernetes operator
sources:
  - https://github.com/enonic/xp-operator
maintainers:
  - name: Slava Bradnitski (vbr@enonic.com)
