apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ec-operator
rules: # TODO: Fix rules
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'