# Create ingress
{{- if not .Values.vhost.spec.skipIngress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.vhost.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
    {{- if .Values.extensions.ecDns }}
    enonic.cloud/dns.hostname: {{ .Values.vhost.spec.host }}
    {{- end }}
    {{- if .Values.vhost.issuer }}
    cert-manager.io/cluster-issuer: {{ .Values.vhost.issuer }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- if .Values.extensions.linkerd }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
    {{- end }}
spec:
  rules:
    - host: {{ .Values.vhost.spec.host }}
      http:
        paths:
          {{- range $mapping := .Values.vhost.spec.mappings }}
          - backend:
              serviceName: {{ $mapping.nodeGroup }}
              servicePort: 8080
            path: {{ $mapping.source }}
          {{- end }}
  {{- if .Values.vhost.issuer }}
  tls:
    - hosts:
        - {{ .Values.vhost.spec.host }}
      secretName: {{ .Values.vhost.name }}
  {{- end }}
---
{{- end }}