# Create ingresses
{{- range $mapping := .Values.vhost.spec.mappings }}
{{- if $mapping.options.ingress }}
{{ $hash := substr 0 10 (sha256sum (list $.Values.vhost.name $mapping.source | join "" )) -}}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $.Values.vhost.name }}-{{ $hash }}
  namespace: {{ $.Values.vhost.namespace }}
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "100"
    {{ $.Values.annotationKeys.vHostName }}: {{ $.Values.vhost.name }}
    enonic.cloud/ingress.cert.manage: "true"
    enonic.cloud/xp7.vhost.mapping.1: |-
      source = {{ $mapping.source }}
      target = {{ $mapping.target }}
      {{- if $mapping.idProviders }}
      idproviders = {{ $mapping.idProviders.default }}
      {{- end }}
spec:
  rules:
    - host: {{ $.Values.vhost.spec.host }}
      http:
        paths:
          - backend:
              serviceName: {{ $mapping.nodeGroup }}
              servicePort: 8080
            path: {{ $mapping.source }}
{{- end }}
{{- end }}