apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: xp7apps.enonic.cloud
spec:
  group: enonic.cloud
  names:
    kind: Xp7App
    listKind: Xp7AppList
    plural: xp7apps
    singular: xp7app
  scope: Namespaced
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            url:
              type: string
  additionalPrinterColumns:
    - name: Url
      type: string
      description: Url to jar
      JSONPath: .spec.url
