apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: xp7deployments.enonic.cloud
spec:
  group: enonic.cloud
  names:
    kind: Xp7Deployment
    listKind: Xp7DeploymentList
    plural: xp7deployments
    singular: xp7deployment
  scope: Cluster
  version: v1alpha1
#  versions:
#    - name: v1alpha1
#      served: true
#      storage: false
#    - name: v1alpha2
#      served: true
#      storage: true
#  conversion:
#    strategy: Webhook
#    webhook:
#      conversionReviewVersions: ["v1beta1"]
#      clientConfig:
#        caBundle: "{CA_CERT}"
#        service:
#          name: kubernetes
#          namespace: default
#          path: /apis/operator.enonic.cloud/conversion
  additionalPrinterColumns:
    - name: Enabled
      type: boolean
      description: XP enabled or not
      JSONPath: .spec.enabled
    - name: Version
      type: string
      description: XP version running
      JSONPath: .spec.xpVersion
    - name: Shared Disk
      type: string
      description: Size of XP shared disk
      JSONPath: .spec.nodesSharedDisk
