apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: xp7apps.enonic.cloud
spec:
  group: enonic.cloud
  names:
    kind: Xp7App
    listKind: Xp7AppList
    plural: xp7apps
    singular: xp7app
  scope: Namespaced
  version: v1alpha1
  additionalPrinterColumns:
    - name: Url
      type: string
      description: Url to jar
      JSONPath: .spec.url
