apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: xpvhosts.enonic.cloud
spec:
  group: enonic.cloud
  names:
    kind: XpVHost
    listKind: XpVHostList
    plural: xpvhosts
    singular: cpvhost
  scope: Namespaced
  version: v1alpha1
  additionalPrinterColumns:
    - name: Host
      type: string
      description: Host
      JSONPath: .spec.host
    - name: Mapping sources
      type: string
      description: Mapping Sources
      JSONPath: .spec.mappings[*].source
    - name: Mapping targets
      type: string
      description: Mapping Sources
      JSONPath: .spec.mappings[*].target
    - name: Cert Self Signed
      type: boolean
      description: Certificate Self Signed
      JSONPath: .spec.certificate.selfSigned
