apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: xp7apps.enonic.cloud
spec:
  group: enonic.cloud
  names:
    kind: Xp7App
    listKind: Xp7AppList
    plural: xp7apps
    singular: xp7app
  scope: Namespaced
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            url:
              type: string
            options:
              type: object
              nullable: true
              properties:
                bootstrap:
                  type: boolean
                appKey:
                  type: string
                  nullable: true
        status:
          type: object
          nullable: true
          properties:
            state:
              type: string
            message:
              nullable: true
              type: string
            fields:
              type: object
              nullable: true
              properties:
                appKey:
                  type: string
                  nullable: true
  additionalPrinterColumns:
    - name: State
      type: string
      description: State
      JSONPath: .status.state
    - name: Msg
      type: string
      description: Message
      JSONPath: .status.message
