apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: xp7vhosts.enonic.cloud
spec:
  group: enonic.cloud
  names:
    kind: Xp7VHost
    listKind: Xp7VHostList
    plural: xp7vhosts
    singular: xp7vhost
  scope: Namespaced
  version: v1alpha1
  additionalPrinterColumns:
    - name: Host
      type: string
      description: Host
      JSONPath: .spec.host
    - name: Nodes
      type: string
      description: Nodes
      JSONPath: .spec.mappings[*].node
    - name: Sources
      type: string
      description: Sources
      JSONPath: .spec.mappings[*].source
    - name: Targets
      type: string
      description: Targets
      JSONPath: .spec.mappings[*].target
    - name: IdProviders
      type: string
      description: IdProviders
      JSONPath: .spec.mappings[*].idProvider