apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: xp7vhosts.enonic.cloud
spec:
  group: enonic.cloud
  names:
    kind: Xp7VHost
    listKind: Xp7VHostList
    plural: xp7vhosts
    singular: xp7vhost
  scope: Namespaced
  preserveUnknownFields: false
  versions:
    - name: v1alpha2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                host:
                  type: string
                options:
                  type: object
                  nullable: true
                  properties:
                    dnsRecord:
                      type: boolean
                    cdn:
                      type: boolean
                certificate:
                  type: object
                  nullable: true
                  properties:
                    authority:
                      type: string
                      enum: ["selfSigned", "letsEncrypt", "letsEncryptStaging", "secret", "clusterIssuer"]
                    identifier:
                      type: string
                      nullable: true
                mappings:
                  type: array
                  items:
                    type: object
                    properties:
                      nodeGroup:
                        type: string
                      source:
                        type: string
                      target:
                        type: string
                      idProviders:
                        type: object
                        nullable: true
                        properties:
                          default:
                            type: string
                          enabled:
                            type: array
                            nullable: true
                            items:
                              type: string
                      options:
                        type: object
                        nullable: true
                        properties:
                          ingress:
                            type: boolean
                          ingressMaxBodySize:
                            type: string
                          statusCake:
                            type: boolean
                          ipWhitelist:
                            type: array
                            items:
                              type: string
                          stickySession:
                            type: boolean
                          sslRedirect:
                            type: boolean
            status:
              type: object
              nullable: true
              properties:
                state:
                  type: string
                  enum : ["ERROR", "PENDING", "READY"]
                message:
                  type: string
                fields:
                  type: object
                  properties:
                    publicIps:
                      type: array
                      items:
                        type: string
                    dnsRecordCreated:
                      type: boolean
    - name: v1alpha1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                host:
                  type: string
                certificate:
                  type: object
                  nullable: true
                  properties:
                    authority:
                      type: string
                mappings:
                  type: array
                  items:
                    type: object
                    properties:
                      node:
                        type: string
                      source:
                        type: string
                      target:
                        type: string
                      idProvider:
                        type: string
                        nullable: true
  additionalPrinterColumns:
    - name: Host
      type: string
      description: Host
      JSONPath: .spec.host
    - name: State
      type: string
      description: State
      JSONPath: .status.state
    - name: Msg
      type: string
      description: Message
      JSONPath: .status.message