# Setup extra config that is mapped to the container
apiVersion: v1
kind: ConfigMap
metadata:
  name: extra-config
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "60"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
{{ tpl (.Files.Glob "extra-config/*").AsConfig . | indent 2 }}