---
kind: "Service"
apiVersion: "v1"
metadata:
  name: "operator"
  namespace: "default"
spec:
  ports:
    - name: "operator"
      protocol: "TCP"
      port: 443
      targetPort: 8443
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "operator"
  namespace: "default"
subsets:
  - addresses:
      - ip: "#IP#"
    ports:
      - port: 8443
        name: "operator"
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.operator.enonic.cloud
spec:
  group: operator.enonic.cloud
  groupPriorityMinimum: 1000
  versionPriority: 15
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZEVENDQXZXZ0F3SUJBZ0lVU2JiOUJwamp5eTlWQ3hxR3U0eStBZ1M0aXBnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZqRVVNQklHQTFVRUF3d0xiWGxoZFhSb2IzSnBkSGt3SGhjTk1qRXdNakU0TVRjeE56QTVXaGNOTXpFdwpNakUyTVRjeE56QTVXakFXTVJRd0VnWURWUVFEREF0dGVXRjFkR2h2Y21sMGVUQ0NBaUl3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dJUEFEQ0NBZ29DZ2dJQkFNTndhTWVaSVRnMjJJbDNldFo5cXFOWDM0WmFtRllkVHJLdk5EbE4KQnkxaFE0TXZPNElZemxLbUpHSWFXb2d1dWJkZVhzbWxhRWNIWU5oS2dYYTFGVUdTSE05bDRiTlhaN2ZOVSthMwpvYnJQSlZUZUx5Mlhtc2NjNnJheURsNW9zMlFSRGI1TzVrQlJuWnBrRWNnQTRCWHJPOEFDS3o5L285TWY4aVZDClBmQ0RoeVBwWTRLalZMeTNEa09pbE8yamZ5Q2JCKzRQcEhHaFY5TEtobEIyZkwrd21aMXJCR1hOSXplWkhwbjcKaENzT0ZkSmlIYnMvaWw4YlBtUUxaQkIzUEdXWjJ1VTUwM1lENk0rN1d2VTE3V3FocEZ6b3dZWWhJOHBsdENrMgpCTGNIYVNlQTVvUTRCYnNQS003N2JpUENQZ0NZVjkvSG5FUEdWdmlHR3dVQWNkMlBMSWkxN3AyaEhBZ3NwaVdpCmlJL3VLZS95d0pEYWp5VWFXOHlQSkRZY2ZiN2xuOW1WMy9KUFQrVTFQeUZicEZ3aDNOTmo3aXEwc0xUTjBNZXEKRzZaUTFwbVdsdlR1NXd4cnJTb1NvaEpLZnl1L1dTcUVuMy9oZXVyQmQ4SGZlUEpFM2t3SUV5Y1ZpdkJpdG5ITgpyWUJzdjcyWFNpb3RDZzdoeUFUZllPRllPNDVpSUEzdzc4SkJZc3JVTlcxVlR5ek9QU002cG9jYzFDaHk4aStpCmdMa0UxOERMYU5oY2VaYy9sWEp4aTVtcE1UTnlyaHduVjR5T002OXh6SmRBdGpodzlxRVk0YWhBMElRd2hqUGEKQXF3U0hjNDY0a1N4TGRCMXlNZVdJN3R6MGVjdWUrdHFKenBqV2lpSnhXNENQdEZVYTJOUnlwdStzcTU3Q3JnUgpVV3B4QWdNQkFBR2pVekJSTUIwR0ExVWREZ1FXQkJSM2I5SEZrTXJmdktpb2d5SzNwQWxETkZBTzBEQWZCZ05WCkhTTUVHREFXZ0JSM2I5SEZrTXJmdktpb2d5SzNwQWxETkZBTzBEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEcKQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUJSTGg4amlTWlZoaE9pdEgvQldXMDVzMm5rak1id2E5Q1hXcy9NVGFueQo5Y3FybmZjRTYxUmpHZ09WMGpPRFdIMzVvMHBtakhOOVJ5OE95MHRwRG5JU0lDWXYzRFlxZXBQVlV4akVyVE9TCnE4bkJXbUR3VWlMVEdIakFZcW9weVhielR6bUVQSTVyVVZnTkttQW1lNGNVRlpuV2UxZDFIS1psUForOEdnQnkKWXI0NkpJVU9HRzl1NVN2RkVqVWZtTWc2RHBmYS9PbHp4V2NRSHBkT2hjejlKYzJlWmpTQXp4U2pvRENRUHdqYQpDU01SU1BJQUNreENJSm1yNVZMNFdGN000a3pTT0dUOU9nKzYvRXJ6K1RLaDVGQ1RBcDFQKzNPU2tYVFJpS1JFCitBTmpvTmNnQlc0SUVGVFdQRkJjZjdDZTdlZU9BalRibkIwUGhmalN6azJxcGd3RDM5dXNLQlFLbHJTTlRjcnkKOXlWZ3QvbTdNMmRLcnJZcGtDUkpMeXYyS2FVdUxaREk5eDNSVVhla1dwYmJlTG1nOWVWVk1zdERmRHVRQ0VEcgpKOTFmYTJVRThTNjJseG9EbmNhQ1hpdGNKTWN6TXk2Ykx2TmxZNlpaTWo0NG5QbERnb0lFSzNpa2FoS0p5ZGdICllZQzVOMFFFaUNoREhid3NFUlVYazRpRG5LdFpENE9XWnRwOHVxSFJnNXJvdVhtNHN5M3ZHTVpOZkhjallRSkYKaE41WU05ejZVVEdzSmhReXM0MXJ3Q0pxWEFrSkkxU1NTTmFBQ3Z2c0JNUHdPQUpVYWVyVzJHZ2hGV2VoWlhWNgpsbzkwUTlVSWg4aUExZVovRkJyb1NlbGNmVDBOdXQzUEZLUHhHOWtnV1p0TW9uMmRZS1ZNY1hxUFNqR1dWczk2CjNBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  service:
    name: "operator"
    namespace: "default"
  version: v1alpha1
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: operator
webhooks:
- name: operator.enonic.cloud
  rules:
    - apiGroups: ["enonic.cloud"]
      operations: ["*"]
      apiVersions: ["*"]
      resources: ["xp7deployments", "xp7vhosts", "xp7apps", "xp7configs", "domains"]
      scope: "*"
  admissionReviewVersions: ["v1"]
  failurePolicy: Fail
  sideEffects: None
  timeoutSeconds: 5
  clientConfig:
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZEVENDQXZXZ0F3SUJBZ0lVU2JiOUJwamp5eTlWQ3hxR3U0eStBZ1M0aXBnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZqRVVNQklHQTFVRUF3d0xiWGxoZFhSb2IzSnBkSGt3SGhjTk1qRXdNakU0TVRjeE56QTVXaGNOTXpFdwpNakUyTVRjeE56QTVXakFXTVJRd0VnWURWUVFEREF0dGVXRjFkR2h2Y21sMGVUQ0NBaUl3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dJUEFEQ0NBZ29DZ2dJQkFNTndhTWVaSVRnMjJJbDNldFo5cXFOWDM0WmFtRllkVHJLdk5EbE4KQnkxaFE0TXZPNElZemxLbUpHSWFXb2d1dWJkZVhzbWxhRWNIWU5oS2dYYTFGVUdTSE05bDRiTlhaN2ZOVSthMwpvYnJQSlZUZUx5Mlhtc2NjNnJheURsNW9zMlFSRGI1TzVrQlJuWnBrRWNnQTRCWHJPOEFDS3o5L285TWY4aVZDClBmQ0RoeVBwWTRLalZMeTNEa09pbE8yamZ5Q2JCKzRQcEhHaFY5TEtobEIyZkwrd21aMXJCR1hOSXplWkhwbjcKaENzT0ZkSmlIYnMvaWw4YlBtUUxaQkIzUEdXWjJ1VTUwM1lENk0rN1d2VTE3V3FocEZ6b3dZWWhJOHBsdENrMgpCTGNIYVNlQTVvUTRCYnNQS003N2JpUENQZ0NZVjkvSG5FUEdWdmlHR3dVQWNkMlBMSWkxN3AyaEhBZ3NwaVdpCmlJL3VLZS95d0pEYWp5VWFXOHlQSkRZY2ZiN2xuOW1WMy9KUFQrVTFQeUZicEZ3aDNOTmo3aXEwc0xUTjBNZXEKRzZaUTFwbVdsdlR1NXd4cnJTb1NvaEpLZnl1L1dTcUVuMy9oZXVyQmQ4SGZlUEpFM2t3SUV5Y1ZpdkJpdG5ITgpyWUJzdjcyWFNpb3RDZzdoeUFUZllPRllPNDVpSUEzdzc4SkJZc3JVTlcxVlR5ek9QU002cG9jYzFDaHk4aStpCmdMa0UxOERMYU5oY2VaYy9sWEp4aTVtcE1UTnlyaHduVjR5T002OXh6SmRBdGpodzlxRVk0YWhBMElRd2hqUGEKQXF3U0hjNDY0a1N4TGRCMXlNZVdJN3R6MGVjdWUrdHFKenBqV2lpSnhXNENQdEZVYTJOUnlwdStzcTU3Q3JnUgpVV3B4QWdNQkFBR2pVekJSTUIwR0ExVWREZ1FXQkJSM2I5SEZrTXJmdktpb2d5SzNwQWxETkZBTzBEQWZCZ05WCkhTTUVHREFXZ0JSM2I5SEZrTXJmdktpb2d5SzNwQWxETkZBTzBEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEcKQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUJSTGg4amlTWlZoaE9pdEgvQldXMDVzMm5rak1id2E5Q1hXcy9NVGFueQo5Y3FybmZjRTYxUmpHZ09WMGpPRFdIMzVvMHBtakhOOVJ5OE95MHRwRG5JU0lDWXYzRFlxZXBQVlV4akVyVE9TCnE4bkJXbUR3VWlMVEdIakFZcW9weVhielR6bUVQSTVyVVZnTkttQW1lNGNVRlpuV2UxZDFIS1psUForOEdnQnkKWXI0NkpJVU9HRzl1NVN2RkVqVWZtTWc2RHBmYS9PbHp4V2NRSHBkT2hjejlKYzJlWmpTQXp4U2pvRENRUHdqYQpDU01SU1BJQUNreENJSm1yNVZMNFdGN000a3pTT0dUOU9nKzYvRXJ6K1RLaDVGQ1RBcDFQKzNPU2tYVFJpS1JFCitBTmpvTmNnQlc0SUVGVFdQRkJjZjdDZTdlZU9BalRibkIwUGhmalN6azJxcGd3RDM5dXNLQlFLbHJTTlRjcnkKOXlWZ3QvbTdNMmRLcnJZcGtDUkpMeXYyS2FVdUxaREk5eDNSVVhla1dwYmJlTG1nOWVWVk1zdERmRHVRQ0VEcgpKOTFmYTJVRThTNjJseG9EbmNhQ1hpdGNKTWN6TXk2Ykx2TmxZNlpaTWo0NG5QbERnb0lFSzNpa2FoS0p5ZGdICllZQzVOMFFFaUNoREhid3NFUlVYazRpRG5LdFpENE9XWnRwOHVxSFJnNXJvdVhtNHN5M3ZHTVpOZkhjallRSkYKaE41WU05ejZVVEdzSmhReXM0MXJ3Q0pxWEFrSkkxU1NTTmFBQ3Z2c0JNUHdPQUpVYWVyVzJHZ2hGV2VoWlhWNgpsbzkwUTlVSWg4aUExZVovRkJyb1NlbGNmVDBOdXQzUEZLUHhHOWtnV1p0TW9uMmRZS1ZNY1hxUFNqR1dWczk2CjNBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    service:
      name: "operator"
      namespace: "default"
      path: /apis/operator.enonic.cloud/v1alpha1/validations
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: operator
webhooks:
  - name: operator.enonic.cloud
    rules:
      - apiGroups: ["enonic.cloud"]
        operations: ["*"]
        apiVersions: ["*"]
        resources: ["xp7deployments", "xp7vhosts", "xp7apps", "xp7configs", "domains"]
        scope: "*"
      - apiGroups: ["networking.k8s.io"]
        operations: ["*"]
        apiVersions: ["v1beta1"]
        resources: ["ingresses"]
        scope: "*"
    admissionReviewVersions: ["v1"]
    failurePolicy: Fail
    sideEffects: None
    timeoutSeconds: 5
    clientConfig:
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZEVENDQXZXZ0F3SUJBZ0lVU2JiOUJwamp5eTlWQ3hxR3U0eStBZ1M0aXBnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZqRVVNQklHQTFVRUF3d0xiWGxoZFhSb2IzSnBkSGt3SGhjTk1qRXdNakU0TVRjeE56QTVXaGNOTXpFdwpNakUyTVRjeE56QTVXakFXTVJRd0VnWURWUVFEREF0dGVXRjFkR2h2Y21sMGVUQ0NBaUl3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dJUEFEQ0NBZ29DZ2dJQkFNTndhTWVaSVRnMjJJbDNldFo5cXFOWDM0WmFtRllkVHJLdk5EbE4KQnkxaFE0TXZPNElZemxLbUpHSWFXb2d1dWJkZVhzbWxhRWNIWU5oS2dYYTFGVUdTSE05bDRiTlhaN2ZOVSthMwpvYnJQSlZUZUx5Mlhtc2NjNnJheURsNW9zMlFSRGI1TzVrQlJuWnBrRWNnQTRCWHJPOEFDS3o5L285TWY4aVZDClBmQ0RoeVBwWTRLalZMeTNEa09pbE8yamZ5Q2JCKzRQcEhHaFY5TEtobEIyZkwrd21aMXJCR1hOSXplWkhwbjcKaENzT0ZkSmlIYnMvaWw4YlBtUUxaQkIzUEdXWjJ1VTUwM1lENk0rN1d2VTE3V3FocEZ6b3dZWWhJOHBsdENrMgpCTGNIYVNlQTVvUTRCYnNQS003N2JpUENQZ0NZVjkvSG5FUEdWdmlHR3dVQWNkMlBMSWkxN3AyaEhBZ3NwaVdpCmlJL3VLZS95d0pEYWp5VWFXOHlQSkRZY2ZiN2xuOW1WMy9KUFQrVTFQeUZicEZ3aDNOTmo3aXEwc0xUTjBNZXEKRzZaUTFwbVdsdlR1NXd4cnJTb1NvaEpLZnl1L1dTcUVuMy9oZXVyQmQ4SGZlUEpFM2t3SUV5Y1ZpdkJpdG5ITgpyWUJzdjcyWFNpb3RDZzdoeUFUZllPRllPNDVpSUEzdzc4SkJZc3JVTlcxVlR5ek9QU002cG9jYzFDaHk4aStpCmdMa0UxOERMYU5oY2VaYy9sWEp4aTVtcE1UTnlyaHduVjR5T002OXh6SmRBdGpodzlxRVk0YWhBMElRd2hqUGEKQXF3U0hjNDY0a1N4TGRCMXlNZVdJN3R6MGVjdWUrdHFKenBqV2lpSnhXNENQdEZVYTJOUnlwdStzcTU3Q3JnUgpVV3B4QWdNQkFBR2pVekJSTUIwR0ExVWREZ1FXQkJSM2I5SEZrTXJmdktpb2d5SzNwQWxETkZBTzBEQWZCZ05WCkhTTUVHREFXZ0JSM2I5SEZrTXJmdktpb2d5SzNwQWxETkZBTzBEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEcKQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUJSTGg4amlTWlZoaE9pdEgvQldXMDVzMm5rak1id2E5Q1hXcy9NVGFueQo5Y3FybmZjRTYxUmpHZ09WMGpPRFdIMzVvMHBtakhOOVJ5OE95MHRwRG5JU0lDWXYzRFlxZXBQVlV4akVyVE9TCnE4bkJXbUR3VWlMVEdIakFZcW9weVhielR6bUVQSTVyVVZnTkttQW1lNGNVRlpuV2UxZDFIS1psUForOEdnQnkKWXI0NkpJVU9HRzl1NVN2RkVqVWZtTWc2RHBmYS9PbHp4V2NRSHBkT2hjejlKYzJlWmpTQXp4U2pvRENRUHdqYQpDU01SU1BJQUNreENJSm1yNVZMNFdGN000a3pTT0dUOU9nKzYvRXJ6K1RLaDVGQ1RBcDFQKzNPU2tYVFJpS1JFCitBTmpvTmNnQlc0SUVGVFdQRkJjZjdDZTdlZU9BalRibkIwUGhmalN6azJxcGd3RDM5dXNLQlFLbHJTTlRjcnkKOXlWZ3QvbTdNMmRLcnJZcGtDUkpMeXYyS2FVdUxaREk5eDNSVVhla1dwYmJlTG1nOWVWVk1zdERmRHVRQ0VEcgpKOTFmYTJVRThTNjJseG9EbmNhQ1hpdGNKTWN6TXk2Ykx2TmxZNlpaTWo0NG5QbERnb0lFSzNpa2FoS0p5ZGdICllZQzVOMFFFaUNoREhid3NFUlVYazRpRG5LdFpENE9XWnRwOHVxSFJnNXJvdVhtNHN5M3ZHTVpOZkhjallRSkYKaE41WU05ejZVVEdzSmhReXM0MXJ3Q0pxWEFrSkkxU1NTTmFBQ3Z2c0JNUHdPQUpVYWVyVzJHZ2hGV2VoWlhWNgpsbzkwUTlVSWg4aUExZVovRkJyb1NlbGNmVDBOdXQzUEZLUHhHOWtnV1p0TW9uMmRZS1ZNY1hxUFNqR1dWczk2CjNBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
      service:
        name: "operator"
        namespace: "default"
        path: /apis/operator.enonic.cloud/v1alpha1/mutations