apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-domain-enonic-net
  namespace: mycloud-mysolution-myenv-myservice
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m

    enonic.cloud/ingress.cert.manage: "true"
    enonic.cloud/xp7.vhost.mapping.1.source: /proxy
    enonic.cloud/xp7.vhost.mapping.1.target: /webapp/com.enonic.app.proxydebug
    enonic.cloud/xp7.vhost.mapping.1.idproviders: system
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: 8080
            path: /
          - backend:
              serviceName: frontend
              servicePort: 8080
            path: /proxy