apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nodeGroup.name }}
  labels:
    xp.managed.config: "true" # TODO: Change
    nodeGroup: {{ .Values.nodeGroup.name }}
    {{- with .Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data: {} # Operator will manage this ConfigMap so leave data empty
