apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeGroup.name }}
  labels:
    {{- with .Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  sessionAffinity: None
  ports:
    - name: xp-main
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    nodeGroup: {{ .Values.nodeGroup.name }}
    {{- with .Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}