# Setup admin user with generated password
apiVersion: enonic.cloud/v1alpha2
kind: Xp7Config
metadata:
  name: {{ .Values.allNodesKey }}-system
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.neverOverwrite }}: true
    {{ $.Values.annotationKeys.applyPriority }}: "70"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with .Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: {{ .Values.allNodesKey }}
  file: system.properties
  dataBase64: false
  data: |-
    xp.name = {{ .Values.deployment.name }}
    xp.suPassword = {sha512}${env.SU_PASS_HASH}
    xp.init.adminUserCreation = false
---
# Disable tour in admin
apiVersion: enonic.cloud/v1alpha2
kind: Xp7Config
metadata:
  name: {{ .Values.allNodesKey }}-admin
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.neverOverwrite }}: true
    {{ $.Values.annotationKeys.applyPriority }}: "70"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with .Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: {{ .Values.allNodesKey }}
  file: com.enonic.xp.app.main.cfg
  dataBase64: false
  data: |-
    tourDisabled = true
---
# Cluster configuration
apiVersion: enonic.cloud/v1alpha2
kind: Xp7Config
metadata:
  name: {{ .Values.allNodesKey }}-cluster
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "70"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: {{ .Values.allNodesKey }}
  file: com.enonic.xp.cluster.cfg
  dataBase64: false
  data: |-
    network.host=0.0.0.0
    network.publish.host=${env.XP_NODE_IP}
    node.name=${env.XP_NODE_NAME}
    cluster.enabled={{ if $.Values.deployment.clustered }}true{{ else }}false{{ end }}
---
{{- if $.Values.deployment.clustered }}
# Hazelcast configuration
apiVersion: enonic.cloud/v1alpha2
kind: Xp7Config
metadata:
  name: {{ .Values.allNodesKey }}-hazelcast
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "70"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: {{ .Values.allNodesKey }}
  file: com.enonic.xp.hazelcast.cfg
  dataBase64: false
  data: |-
    clusterConfigDefaults=false
    system.hazelcast.initial.min.cluster.size=${env.XP_HZ_MIN_SIZE}
    network.join.tcpIp.enabled=false
    network.join.kubernetes.enabled=true
    {{- if $.Values.settings.hzApiDiscovery }}
    network.join.kubernetes.serviceName={{ $.Values.discoveryService }}
    network.join.kubernetes.namespace={{ $.Values.deployment.namespace }}
    network.join.kubernetes.kubernetesApiRetries=10
    network.join.kubernetes.resolveNotReadyAddresses=true
    partition.group.enabled=true
    partition.group.groupType=NODE_AWARE
    {{- else }}
    network.join.kubernetes.serviceDns={{ $.Values.discoveryService }}.{{ $.Values.deployment.namespace }}.svc.cluster.local
    {{- end }}
---
{{- end }}
# Logging
apiVersion: enonic.cloud/v1alpha2
kind: Xp7Config
metadata:
  name: {{ .Values.allNodesKey }}-logback
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.neverOverwrite }}: true
    {{ $.Values.annotationKeys.applyPriority }}: "70"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: {{ .Values.allNodesKey }}
  file: logback.xml
  dataBase64: false
  data: |-
    <?xml version="1.0"?>
    <configuration scan="true" scanPeriod="60 seconds">

      <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${xp.home}/logs/server.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
          <fileNamePattern>${xp.home}/logs/server.%d{yyyy-MM-dd}.%i.log</fileNamePattern>
          <maxFileSize>100MB</maxFileSize>
          <maxHistory>7</maxHistory>
          <totalSizeCap>3GB</totalSizeCap>
        </rollingPolicy>
        <encoder>
          <pattern>%date{ISO8601} %-5level %logger{36} - %msg%n</pattern>
        </encoder>
      </appender>

      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <withJansi>true</withJansi>
        <encoder>
          <pattern>%date{ISO8601} %-5level %logger{36} - %msg%n</pattern>
        </encoder>
      </appender>

      <root level="info">
        <appender-ref ref="STDOUT"/>
        <appender-ref ref="FILE"/>
      </root>

      <logger name="Events.Service" level="WARN" additivity="false">
        <appender-ref ref="STDOUT"/>
        <appender-ref ref="FILE"/>
      </logger>

      <logger name="Events.Bundle" level="WARN" additivity="false">
        <appender-ref ref="STDOUT"/>
        <appender-ref ref="FILE"/>
      </logger>

    </configuration>
