# Setup Xp7Config for each node
{{- range $nodeGroup := .Values.deployment.spec.nodeGroups }}
# VHost configuration
apiVersion: enonic.cloud/v1alpha2
kind: Xp7Config
metadata:
  name: {{ $nodeGroup.name }}-vhosts
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.neverOverwrite }}: true
    {{ $.Values.annotationKeys.applyPriority }}: "71"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: {{ $nodeGroup.name }}
  file: com.enonic.xp.web.vhost.cfg
  dataBase64: false
  data: |-
    enabled = true
---
# Elastic Search configuration
apiVersion: enonic.cloud/v1alpha2
kind: Xp7Config
metadata:
  name: {{ $nodeGroup.name }}-elasticsearch
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "71"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: {{ $nodeGroup.name }}
  file: com.enonic.xp.elasticsearch.cfg
  dataBase64: false
  data: |-
    http.enabled=true
    cluster.name={{ $.Values.deployment.name }}
    {{- if not $.Values.deployment.clustered }}
    index.auto_expand_replicas=0-all
    {{ else }}
    node.master=${env.XP_IS_MASTER}
    node.data=${env.XP_IS_DATA}
    gateway.expected_master_nodes=${env.XP_ES_MIN_MASTERS}
    gateway.expected_data_nodes=${env.XP_ES_MIN_DATAS}
    gateway.recover_after_time=5m
    discovery.zen.minimum_master_nodes=${env.XP_ES_MIN_MASTERS}
    discovery.unicast.sockets={{ $.Values.discoveryService }}.{{ $.Values.deployment.namespace }}.svc.cluster.local
    network.tcp.keep_alive=true
    index.auto_expand_replicas=1-all
    {{- end }}
---
{{- end }}
