# Default vHosts

# Health check for Kubernetes
apiVersion: enonic.cloud/v1alpha2
kind: Xp7VHost
metadata:
  name: {{ .Values.allNodesKey }}-healthcheck
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "80"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with .Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: healthcheck
  options:
    dnsRecord: false
    cdn: false
  mappings:
    - nodeGroup: {{ .Values.allNodesKey }}
      source: /
      target: /webapp/com.enonic.app.alive
      options:
        ingress: false

---

# Access to localhost if OPs want to do 'kubectl port-forward'
apiVersion: enonic.cloud/v1alpha2
kind: Xp7VHost
metadata:
  name: {{ .Values.allNodesKey }}-localhost
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "80"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with .Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: localhost
  options:
    dnsRecord: false
    cdn: false
  mappings:
    - nodeGroup: {{ .Values.allNodesKey }}
      source: /
      target: /
      idProviders:
        default: system
      options:
        ingress: false