# Setup
apiVersion: v1
kind: Secret
metadata:
  name: su
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.neverOverwrite }}: true
    {{ $.Values.annotationKeys.applyPriority }}: "60"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  pass: {{ $.Values.deployment.suPass | b64enc }}
  passHash: {{ $.Values.deployment.suPassHash | b64enc }}