# Setup shared volumes persistent claims
{{- range $name, $size := .Values.deployment.spec.nodesSharedDisks }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}
  labels:
    {{- if not (has $name $.Values.volumeBackups) }}
    velero.io/exclude-from-backup: true
    {{- end }}
    {{ $.Values.labels.managed }}: true
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  storageClassName: {{ $.Values.storage.shared.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $size }}
{{- end }}