# Setup extra config that is mapped to the container
apiVersion: v1
kind: ConfigMap
metadata:
  name: extra-config
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.neverOverwrite }}: true
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  java.security.properties: |-
    networkaddress.cache.ttl=30