# Default vHosts

# Health check for Kubernetes
apiVersion: enonic.cloud/v1alpha2
kind: Xp7VHost
metadata:
  name: healthcheck
  labels:
    {{- with .Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: healthcheck
  skipIngress: true
  mappings:
    - nodeGroup: all
      source: /
      target: /webapp/com.enonic.app.alive

---

# Access to localhost if OPs want to do 'kubectl port-forward'
apiVersion: enonic.cloud/v1alpha2
kind: Xp7VHost
metadata:
  name: localhost
  labels:
    {{- with .Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: localhost
  skipIngress: true
  mappings:
    - nodeGroup: all
      source: /
      target: /