# Default vHosts

# Health check for Kubernetes
apiVersion: enonic.cloud/v1alpha2
kind: Xp7VHost
metadata:
  name: healthcheck
  namespace: {{ $.Values.deployment.namespace }}
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with .Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: healthcheck
  options:
    ingress: false
  mappings:
    - nodeGroup: all
      source: /
      target: /webapp/com.enonic.app.alive

---

# Access to localhost if OPs want to do 'kubectl port-forward'
apiVersion: enonic.cloud/v1alpha2
kind: Xp7VHost
metadata:
  name: localhost
  namespace: {{ $.Values.deployment.namespace }}
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with .Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: localhost
  options:
    ingress: false
  mappings:
    - nodeGroup: all
      source: /
      target: /
      idProviders:
        default: system