# Setup cloud api service account
{{- if $.Values.cloudApiSa }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-secrets
  namespace: {{ $.Values.deployment.namespace }}
rules:
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-api-read-secrets
  namespace: {{ $.Values.deployment.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-secrets
subjects:
- kind: ServiceAccount
  name: {{ $.Values.cloudApiSa.name }}
  namespace: {{ $.Values.cloudApiSa.namespace }}
{{- end }}
