# Setup extra config that is mapped to the container
apiVersion: v1
kind: ConfigMap
metadata:
  name: extra-config
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.neverOverwrite }}: true
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  init.sh: |-
    # Install initApps
    cat {{ $.Values.extraConfigLocation }}/initApps.txt | xargs -I {} app.sh add {}
  initApps.txt: |-
    {{- range $app := .Values.initApps }}
    {{ $app }}
    {{- end }}
  java.security.properties: |-
    networkaddress.cache.ttl=30