# Setup admin user with generated password
apiVersion: enonic.cloud/v1alpha2
kind: Xp7Config
metadata:
  name: all-system
  annotations:
    {{ $.Values.annotations.neverOverwrite }}: true
  labels:
    {{ $.Values.labels.managed }}: true
    {{- with .Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: all
  file: system.properties
  data: |-
    xp.suPassword = {sha512}${env.SU_PASS_HASH}
    xp.init.adminUserCreation = false

---

# Disable tour in admin
apiVersion: enonic.cloud/v1alpha2
kind: Xp7Config
metadata:
  name: all-admin
  annotations:
    {{ $.Values.annotations.neverOverwrite }}: true
  labels:
    {{ $.Values.labels.managed }}: true
    {{- with .Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: all
  file: com.enonic.xp.app.main.cfg
  data: |-
    tourDisabled = true

---

# Set session store
apiVersion: enonic.cloud/v1alpha2
kind: Xp7Config
metadata:
  name: all-sessionstore
  annotations:
    {{ $.Values.annotations.neverOverwrite }}: true
  labels:
    {{ $.Values.labels.managed }}: true
    {{- with .Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: all
  file: com.enonic.xp.web.sessionstore.cfg
  data: |-
    {{- if $.Values.deployment.clustered }}
    storeMode=replicated
    {{- else }}
    storeMode=non-persistent
    {{- end }}