{{- range $nodeGroupName, $nodeGroup := .Values.deployment.spec.nodeGroups }}
---
apiVersion: enonic.cloud/v1alpha1
kind: Xp7Config
metadata:
  name: {{ $nodeGroupName }}-cluster
  labels:
    nodeGroup: {{ $nodeGroupName }}
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: {{ $nodeGroupName }}
  file: com.enonic.xp.cluster.cfg
  data: |-
  {{- if $.Values.deployment.clustered }}
    # TODO
  {{- else }}
    cluster.enabled=false
  {{- end }}

---
apiVersion: enonic.cloud/v1alpha1
kind: Xp7Config
metadata:
  name: {{ $nodeGroupName }}-elasticsearch
  labels:
    nodeGroup: {{ $nodeGroupName }}
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: {{ $nodeGroupName }}
  file: com.enonic.xp.elasticsearch.cfg
  data: |-
  {{- if $.Values.deployment.clustered }}
    # TODO
  {{- else }}
    http.enabled=false
  {{- end }}

---
apiVersion: enonic.cloud/v1alpha1
kind: Xp7Config
metadata:
  name: {{ $nodeGroupName }}-vhosts
  labels:
    managedBy: ec-operator
    nodeGroup: {{ $nodeGroupName }}
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: {{ $nodeGroupName }}
  file: com.enonic.xp.web.vhost.cfg
  data: |-
    enabled = true
    # Operator will manage this Xp7Config so leave data empty
{{- end }}