# Setup Xp7Config for each node
{{- range $nodeGroupName, $nodeGroup := .Values.deployment.spec.nodeGroups }}

# Cluster configuration
apiVersion: enonic.cloud/v1alpha2
kind: Xp7Config
metadata:
  name: {{ $nodeGroupName }}-cluster
  labels:
    {{ $.Values.labels.managed }}: true
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: {{ $nodeGroupName }}
  file: com.enonic.xp.cluster.cfg
  data: |-
  {{- if not $.Values.deployment.clustered }}
    cluster.enabled=false
  {{- else }}
    cluster.enabled=true
    node.name=${env.XP_NODE_NAME}
    discovery.unicast.hosts={{ $.Values.deployment.discoveryHosts | join "," }}
    network.publish.host=${env.XP_NODE_NAME}.{{ $.Values.allNodesKey }}
  {{- if $.Values.extensions.linkerd.enabled }}
      network.host=127.0.0.1
    {{- else }}
      network.host=${env.XP_NODE_NAME}.{{ $.Values.allNodesKey }}
    {{- end }}
  {{- end }}

---

# Elastic Search configuration
apiVersion: enonic.cloud/v1alpha2
kind: Xp7Config
metadata:
  name: {{ $nodeGroupName }}-elasticsearch
  labels:
    {{ $.Values.labels.managed }}: true
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: {{ $nodeGroupName }}
  file: com.enonic.xp.elasticsearch.cfg
  data: |-
  {{- if not $.Values.deployment.clustered }}
    http.enabled=false
  {{- else }}
    node.master={{ if $nodeGroup.master }}true{{ else }}false{{ end }}
    node.data={{ if $nodeGroup.data }}true{{ else }}false{{ end }}
    cluster.name={{ $.Values.deployment.name }}
    http.enabled=false
    gateway.expected_master_nodes={{ $.Values.deployment.minimumMasterNodes }}
    gateway.expected_data_nodes={{ $.Values.deployment.minimumDataNodes }}
    gateway.recover_after_time=5m
    discovery.zen.minimum_master_nodes={{ $.Values.deployment.minimumMasterNodes }}
    network.tcp.keep_alive=true
  {{- end }}

---
{{- end }}