# Setup service pointing to each nodeGroup
{{- range $nodeGroupName, $nodeGroup := .Values.deployment.spec.nodeGroups }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $nodeGroupName }}
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{ $.Values.labelKeys.nodeGroup }}: {{ $nodeGroupName }}
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  sessionAffinity: None
  selector:
    {{ $.Values.labelKeys.nodeGroup }}: {{ $nodeGroupName }}
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
    - name: xp-metrics
      port: 2609
      targetPort: 2609
      protocol: TCP
    - name: xp-management
      port: 4848
      targetPort: 4848
      protocol: TCP
    - name: xp-main
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: es-api
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: es-transport
      port: 9300
      targetPort: 9300
      protocol: TCP
---
{{- end }}