# Setup ConfigMap for each node group
{{- range $nodeGroup := .Values.deployment.spec.nodeGroups }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $nodeGroup.name }}
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.neverOverwrite }}: true
    {{ $.Values.annotationKeys.applyPriority }}: "50"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{ $.Values.labelKeys.nodeGroup }}: {{ $nodeGroup.name }}
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data: {} # Operator will manage this ConfigMap so leave data empty
---
{{- end }}
