# Create StatefulSet for each nodeGroup
{{- range $nodeGroupName, $nodeGroup := .Values.deployment.spec.nodeGroups }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $nodeGroupName }}
  labels:
    nodeGroup: {{ $nodeGroupName }}
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  serviceName: all
  replicas: {{ $nodeGroup.replicas }}
  revisionHistoryLimit: 10
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      nodeGroup: {{ $nodeGroupName }}
      {{- with $.Values.defaultLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      annotations:
        {{- if index $.Values "extensions.linkerd" }}
        linkerd.io/inject: enabled
        {{- end }}
      labels:
        nodeGroup: {{ $nodeGroupName }}
        {{- with $.Values.defaultLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

      securityContext:
        fsGroup: 0
        runAsUser: {{ $.Values.user }}

      initContainers:
        {{- if $.Values.storage.shared.forcePermissions }}
        - name: shared-storage-permissions
          image: alpine:3.10
          imagePullPolicy: IfNotPresent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext:
            privileged: true
            runAsUser: 0
          resources: {}
          volumeMounts:
            {{- range $volumeName, $volumeSize := $.Values.deployment.spec.nodesSharedDisks }}
            - name: {{ $volumeName }}
              mountPath: {{ index $.Values.volumeMounts $volumeName }}
            {{- end }}
          command:
            - ash
            - -c
            - {{ range $volumeName, $volumeSize := $.Values.deployment.spec.nodesSharedDisks }}chown 1337:0 {{ index $.Values.volumeMounts $volumeName }}; {{ end }}
        {{- end }}
        - name: configure-sysctl
          image: {{ $.Values.image }}
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext:
            privileged: true
            runAsUser: 0
          resources: {}
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144

        # This init container so the node does not get the exception: Cannot create host entry for value
        - name: wait-for-dns
          image: alpine:3.10
          imagePullPolicy: IfNotPresent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources: {}
          env:
            - name: XP_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          command:
            - ash
            - -c
            - sleep 5; x="0"; while [ "$x" == "0" ]; do nslookup ${XP_NODE_NAME}.{{ $.Values.deployment.allNodeGroupsKey }} && x="1"; sleep 2; done

      containers:
        - name: exp
          image: {{ $.Values.image }}
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: {{ $.Values.user }}

          resources:
            limits:
              cpu: {{ $nodeGroup.resources.cpu }}
              memory: {{ $nodeGroup.resources.memory }}
            requests:
              cpu: {{ $nodeGroup.resources.cpu }}
              memory: {{ $nodeGroup.resources.memory }}

          ports:
          - name: xp-stats
            containerPort: 2609
            protocol: TCP
          - name: xp-main
            containerPort: 8080
            protocol: TCP
          - name: es-http
            containerPort: 9200
            protocol: TCP
          - name: es-transport
            containerPort: 9300
            protocol: TCP

          env:
          - name: XP_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: XP_NODE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: SU_PASS_HASH
            valueFrom:
              secretKeyRef:
                name: su
                key: passHash
                optional: false
          {{- range $key, $value := $nodeGroup.env }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
          {{- if not (index $nodeGroup.env "JAVA_OPTS") }}
          - name: JAVA_OPTS
            value: '-Djava.security.properties={{ $.Values.extraConfigLocation }}/java.security.properties -XX:+UseContainerSupport -XX:MinRAMPercentage=20 -XX:InitialRAMPercentage=30
                        -XX:MaxRAMPercentage={{ if and $nodeGroup.master (not $nodeGroup.data) }}75{{ else }}50{{ end }} -Djsse.enableSNIExtension=true -XX:+UseConcMarkSweepGC
                        -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60
                        -XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark -XX:-HeapDumpOnOutOfMemoryError
                        -XX:HeapDumpPath={{ $.Values.heapDumpLocation }}/oom.hprof'
          {{- end }}
          livenessProbe:
            {{- with $.Values.livenessProbe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

          readinessProbe:
            {{- with $.Values.readinessProbe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

          volumeMounts:
            - name: config
              mountPath: {{ $.Values.configLocation }}
            - name: extra-config
              mountPath: {{ $.Values.extraConfigLocation }}
            {{- range $volumeName, $volumeSize := $nodeGroup.resources.disks }}
            - name: {{ $volumeName }}
              mountPath: {{ index $.Values.volumeMounts $volumeName }}
            {{- end }}
            {{- range $volumeName, $volumeSize := $.Values.deployment.spec.nodesSharedDisks }}
            - name: {{ $volumeName }}
              mountPath: {{ index $.Values.volumeMounts $volumeName }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            defaultMode: "420"
            name: {{ $nodeGroupName }}
        - name: extra-config
          configMap:
            defaultMode: "420"
            name: extra-config
        {{- range $volumeName, $volumeSize := $.Values.deployment.spec.nodesSharedDisks }}
        - name: {{ $volumeName }}
          persistentVolumeClaim:
            claimName: {{ $volumeName }}
        {{- end }}

  volumeClaimTemplates:
    {{- range $volumeName, $volumeSize := $nodeGroup.resources.disks }}
    - metadata:
        name: {{ $volumeName }}
        labels:
          nodeGroup: {{ $nodeGroupName }}
          {{- with $.Values.defaultLabels }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      spec:
        volumeMode: Filesystem
        storageClassName: {{ $.Values.storage.default.storageClassName }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ $volumeSize }}
    {{- end }}
---
{{- end }}