# Setup service pointing to each nodeGroup
{{- range $nodeGroupName, $nodeGroup := .Values.deployment.spec.nodeGroups }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $nodeGroupName }}
  labels:
    nodeGroup: {{ $nodeGroupName }}
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  sessionAffinity: None
  selector:
    nodeGroup: {{ $nodeGroupName }}
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
    - name: xp-metrics
      port: 2609
    - name: xp-management
      port: 4848
    - name: xp-main
      port: 8080
    - name: es-api
      port: 9200
    - name: es-transport
      port: 9300
---
{{- end }}