# Setup Xp7Config for each node
{{- range $nodeGroup := .Values.deployment.spec.nodeGroups }}
# VHost configuration
apiVersion: enonic.cloud/v1alpha2
kind: Xp7Config
metadata:
  name: {{ $nodeGroup.name }}-vhosts
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.neverOverwrite }}: true
    {{ $.Values.annotationKeys.applyPriority }}: "71"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: {{ $nodeGroup.name }}
  file: com.enonic.xp.web.vhost.cfg
  dataBase64: false
  data: |-
    enabled = true
---
{{- if not $.Values.deployment.clustered }}
# Elastic Search non clustered configuration
apiVersion: enonic.cloud/v1alpha2
kind: Xp7Config
metadata:
  name: {{ $nodeGroup.name }}-elasticsearch
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "71"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: {{ $nodeGroup.name }}
  file: com.enonic.xp.elasticsearch.cfg
  dataBase64: false
  data: |-
    http.enabled=true
    cluster.name={{ $.Values.deployment.name }}
---
{{- else }}
# Elastic Search clustered configuration
apiVersion: enonic.cloud/v1alpha2
kind: Xp7Config
metadata:
  name: {{ $nodeGroup.name }}-elasticsearch
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.neverOverwrite }}: true
    {{ $.Values.annotationKeys.applyPriority }}: "71"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodeGroup: {{ $nodeGroup.name }}
  file: com.enonic.xp.elasticsearch.cfg
  dataBase64: false
  data: |-
    http.enabled=true
    cluster.name={{ $.Values.deployment.name }}
    node.master={{ if $nodeGroup.master }}true{{ else }}false{{ end }}
    node.data={{ if $nodeGroup.data }}true{{ else }}false{{ end }}
    gateway.expected_master_nodes={{ $.Values.deployment.minimumMasterNodes }}
    gateway.expected_data_nodes={{ $.Values.deployment.minimumDataNodes }}
    gateway.recover_after_time=5m
    discovery.zen.minimum_master_nodes={{ $.Values.deployment.minimumMasterNodes }}
    discovery.unicast.sockets={{ $.Values.discoveryService }}.{{ $.Values.deployment.namespace }}.svc.cluster.local
    network.tcp.keep_alive=true
{{- end }}
---
{{- end }}