defaultStorageClass: standard

livenessProbe:
  failureThreshold: 4
  httpGet:
    httpHeaders:
      - name: Host
        value: healthcheck
    path: /
    port: 8080
    scheme: HTTP
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 1

readinessProbe:
  failureThreshold: 5
  httpGet:
    httpHeaders:
      - name: Host
        value: healthcheck
    path: /
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 1