imagePullPolicy: IfNotPresent

livenessProbe:
  failureThreshold: 4
  httpGet:
    httpHeaders:
      - name: Host
        value: healthcheck
    path: /
    port: 8080
    scheme: HTTP
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 1

readinessProbe:
  failureThreshold: 5
  httpGet:
    httpHeaders:
      - name: Host
        value: healthcheck
    path: /
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 1

volumeMounts:
  export: /enonic-xp/home/data
  index: /enonic-xp/home/repo/index
  work: /enonic-xp/home/work
  blobstore: /enonic-xp/home/repo/blob
  snapshots: /enonic-xp/home/snapshots

volumeBackups: ["blobstore", "snapshots"]

heapDumpLocation: /enonic-xp/home/exports/dumps
configLocation: /enonic-xp/home/config
extraConfigLocation: /enonic-xp/home/extra-config

user: 1337
fsGroup: 0

terminationGracePeriodSeconds: 30
updateStrategy: RollingUpdate
initContainersImage: alpine:3.10

resources:
  cpu:
    defaultRequests: null
  memory:
    defaultRequests: null

storage:
  default:
    storageClassName: standard
    annotations: {}
  shared:
    storageClassName: standard
    annotations: {}

# Filled in by operator
# deployment:
#   name: gbb-tests-qa
#   clustered: false
#   spec:
#     ...

extensions:
  linkerd:
    enabled: false