imagePullPolicy: IfNotPresent

volumeMounts:
  export: /enonic-xp/home/data
  index: /enonic-xp/home/repo/index
  work: /enonic-xp/home/work
  blobstore: /enonic-xp/home/repo/blob
  snapshots: /enonic-xp/home/snapshots
  deploy: /enonic-xp/home/deploy

volumeBackups: ["blobstore", "snapshots"]

heapDumpLocation: /enonic-xp/home/data
configLocation: /enonic-xp/home/config
extraConfigLocation: /enonic-xp/home/extra-config
setEnvLocation: /enonic-xp/home/setenv.sh

discoveryService: cluster-discovery

securityContext:
  user: 1337
  fsGroup: 0

terminationGracePeriodSeconds: 600 # 10 minutes
updateStrategy: RollingUpdate
initContainersImage: alpine:3.10

resources:
  cpu:
    defaultRequests: null
  memory:
    defaultRequests: null

storage:
  default:
    storageClassName: standard
    annotations: {}
  shared:
    storageClassName: standard
    annotations: {}

extensions:
  linkerd:
    enabled: false

initApps:
  - https://repo.enonic.com/public/com/enonic/app/snapshotter/3.0.1/snapshotter-3.0.1.jar

# Filled in by operator
# deployment:
#   name: gbb-tests-qa
#   clustered: false
#   spec:
#     ...