imagePullPolicy: IfNotPresent

# Fails after 2 minutes
livenessProbe:
  failureThreshold: 4
  httpGet:
    httpHeaders:
      - name: Host
        value: healthcheck
    path: /
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 60
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 1

# Fails after 2 minutes
readinessProbe:
  failureThreshold: 12
  httpGet:
    httpHeaders:
      - name: Host
        value: healthcheck
    path: /
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 45
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

volumeMounts:
  export: /enonic-xp/home/data
  index: /enonic-xp/home/repo/index
  work: /enonic-xp/home/work
  blobstore: /enonic-xp/home/repo/blob
  snapshots: /enonic-xp/home/snapshots

volumeBackups: ["blobstore", "snapshots"]

heapDumpLocation: /enonic-xp/home/exports/dumps
configLocation: /enonic-xp/home/config
extraConfigLocation: /enonic-xp/home/extra-config
deployLocation: /enonic-xp/home/deploy

securityContext:
  user: 1337
  fsGroup: 0

terminationGracePeriodSeconds: 30
updateStrategy: RollingUpdate
initContainersImage: alpine:3.10

resources:
  cpu:
    defaultRequests: null
  memory:
    defaultRequests: null

storage:
  default:
    storageClassName: standard
    annotations: {}
  shared:
    storageClassName: standard
    annotations: {}

extensions:
  linkerd:
    enabled: false

initApps:
  - https://repo.enonic.com/public/com/enonic/app/alive/2.0.0/alive-2.0.0.jar
  - https://repo.enonic.com/public/com/enonic/app/snapshotter/2.1.1/snapshotter-2.1.1.jar

# Filled in by operator
# deployment:
#   name: gbb-tests-qa
#   clustered: false
#   spec:
#     ...